docker stop base
docker rm base
rm -f /home/ubuntu20/Workspace/Datasets/log.txt
rm -rf /home/ubuntu20/Workspace/Datasets/10s
rm -rf /home/ubuntu20/Workspace/Datasets/2s_1 
rm -rf /home/ubuntu20/Workspace/Datasets/2s_2
rm -rf /home/ubuntu20/Workspace/Datasets/2s_3
rm -rf /home/ubuntu20/Workspace/Datasets/2s_4
rm -rf /home/ubuntu20/Workspace/Datasets/10s_10ms
rm -rf /home/ubuntu20/Workspace/Datasets/10s_100ms
rm -rf /home/ubuntu20/Workspace/Datasets/malwares/Valid_ELF_20200405
